server {
    listen 80;
    server_name localhost;
    root /var/www/html/public; # Specifies the public root folder
    index index.php index.html index.htm;
    charset utf-8;

    location / {
        # Try serving the requested URI directly, or fall back to index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000; # Pass PHP requests to the php-fpm service
        fastcgi_index index.php;
        include fastcgi.conf;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_read_timeout 3000s;
            fastcgi_connect_timeout 3000s;
            fastcgi_send_timeout 3000s;
    }

    location ~ /\.ht {
        deny all;
    }
}
